### ISSUE TITLE
Dataset Viewer issue for voxlingua107

### ISSUE THREAD

**Issue by msk-ms** [huggingface/datasets-server#1008]

**Comment by albertvillanova** [comment]
Thanks for reporting, @msk-ms.

Which dataset do you report? There are 2 datasets in the Hub with that name:
- "TalTechNLP/VoxLingua107": https://huggingface.co/datasets/TalTechNLP/VoxLingua107
- "lilitket/voxlingua107": https://huggingface.co/datasets/lilitket/voxlingua107

And the root issue with both datasets is not the datasets viewer itself but their dataset: non of them can be loaded:
- "TalTechNLP/VoxLingua107": it has an issue with their loading script: they try to use `datasets.Split.DEV` and this does not exist. The error in their viewer suggests opening an issue in their Community tab instead of here: https://huggingface.co/datasets/TalTechNLP/VoxLingua107/discussions
- "lilitket/voxlingua107": it has neither a loading script nor data files, their dataset is empty: https://huggingface.co/datasets/lilitket/voxlingua107/tree/main
  - Therefore, it is normal that the viewer shows the error "ResponseNotFound"
  - I recommend you to contact the authors in their community tab, by opening a new discussion: https://huggingface.co/datasets/lilitket/voxlingua107/discussions
