### ISSUE TITLE
Dataset Viewer issue for cryscan/multilingual-share

### ISSUE THREAD

**Issue by cryscan** [huggingface/datasets-server#1013]
### Link

https://huggingface.co/datasets/cryscan/multilingual-share

### Description

The dataset viewer is not working for dataset cryscan/multilingual-share.

Error details:

```
Error code:   JobRunnerCrashedError

```

Maybe reset the pointer to [this file](https://huggingface.co/datasets/cryscan/multilingual-share/blob/main/sharegpt_90k_unfiltered_multilang_fixed.json)?

**Comment by severo** [comment]
keep open

**Comment by albertvillanova** [comment]
Thanks for reporting, @cryscan.

Please note that the job crashed because you are trying to load into RAM memory JSON files that are quite large (more than 1 GB). I guess many potential users would face the same issue if their machines do not have enough RAM memory.

If you would like to support loading your dataset in machines with lower RAM, you should:
- either change the format of your data files, from JSON to JSON-lines, so that the data files can be loaded in memory line by line, thus with manageable RAM requirements
- or split your JSON files into smaller files (around maximum 500 MB each), so that each of them can be loaded in memory

I have opened a discussion in the Community tab of the dataset: https://huggingface.co/datasets/cryscan/multilingual-share/discussions/1
Let's continue the discussion there!
