### ISSUE TITLE
Dataset Viewer issue for nyuuzyou/AnimeHeadsv3

### ISSUE THREAD

**Issue by nyuuzyou** [huggingface/datasets-server#1073]
### Link

https://huggingface.co/datasets/nyuuzyou/AnimeHeadsv3

### Description

The dataset viewer is not working for dataset nyuuzyou/AnimeHeadsv3.

Error details:

```
Error code:   ResponseNotReady

```
The dataset status has been showing as "ResponseNotReady" for the past six days, and sometimes it briefly changes to "ResponseNotFound". I am not sure if this is a bug or if there is an issue with the dataset itself.

**Comment by severo** [comment]
Thanks for reporting. The dataset viewer now shows the root issue:

<img width="1053" alt="Capture d’écran 2023-04-21 à 13 20 39" src="https://user-images.githubusercontent.com/1676121/233623579-f4ce7fc9-4dc9-4a51-a932-3dc9b2f62e22.png">

Maybe @albertvillanova can help on the details of why the dataset is not loading.

**Comment by albertvillanova** [comment]
Yes, the issue is not with the dataset viewer, but with the dataset: it does not load.
```python
from datasets import load_dataset

ds = load_dataset("nyuuzyou/AnimeHeadsv3")
```
The reason is that the directory structure within the ZIP archive files is not supported.
```
images
   ├── 0001_bel1c1i1_jpg.rf.1a4afbb24eedb9665bf5b590b3b7ceed.jpg
   ├── ...
labels
   ├── 0001_bel1c1i1_jpg.rf.1a4afbb24eedb9665bf5b590b3b7ceed.txt
   ├── ...
```

For image datasets to be supported without a loading script, they need to have a very specific `ImageFolder` structure. You can get more information here: [Create an image dataset](https://huggingface.co/docs/datasets/image_dataset).

I have created a discussion in the "Community" tab of the dataset: https://huggingface.co/datasets/nyuuzyou/AnimeHeadsv3/discussions/1
Let's continue the discussion there.

On the other hand, I agree that from the `datasets` library, we should give a more informative error message.
I am working on this.
