### ISSUE TITLE
Dataset Viewer issue for mehdie/sefaria

### ISSUE THREAD

**Issue by tomersagi** [huggingface/datasets-server#1111]
### Link

https://huggingface.co/datasets/mehdie/sefaria

### Description

The dataset viewer is not working for dataset mehdie/sefaria.

Error details:

```
Error code:   UnexpectedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @tomersagi.

Please note that the issue is not specifically related to the viewer, but with your dataset itself: your dataset is not loading.

Note that your loading script should be named as the repo, that is "sefaria.py". I'm opening a discussion in the Community tab of your dataset: https://huggingface.co/datasets/mehdie/sefaria/discussions/1
Let's continue the discussion there!
