### ISSUE TITLE
Dataset Viewer issue for Numerati/numerai-datasets

### ISSUE THREAD

**Issue by roxyrong** [huggingface/datasets-server#1143]
### Link

https://huggingface.co/datasets/Numerati/numerai-datasets

### Description

The dataset viewer is not working for dataset Numerati/numerai-datasets.

Error details:

```
Error code:   UnexpectedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @roxyrong.

Please note that the current error is `TooManyColumnsError`:
```
The number of columns (1223) exceeds the maximum supported number of columns (1000). This is a current limitation of the datasets viewer. You can reduce the number of columns if you want the viewer to work.
```

As the message says, this is a current limitation of the viewer and in the future we could increase the number of supported columns. In the meantime, in order to make the viewer work, the only solution is to reduce the number of rows.
