### ISSUE TITLE
Dataset Viewer issue for GEM/wiki_lingua

### ISSUE THREAD

**Issue by surya-narayanan** [huggingface/datasets-server#1153]
### Link

https://huggingface.co/datasets/GEM/wiki_lingua

### Description

The dataset viewer is not working for dataset GEM/wiki_lingua.

Error details:

```
Error code:   JobRunnerCrashedError
Traceback:    The previous step failed, the error is copied to this step:  kind='/config-names' dataset='GEM/wiki_lingua' config=None split=None---
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @surya-narayanan.

Please note that yesterday we had an outage issue impacting the Hugging Face Hub and many viewer processes crashed. The issue is already fixed and all viewers will eventually be updated.

For this specific dataset (GEM/wiki_lingua) please note that streaming is not supported (because the source data file is a TAR archive). The viewer uses the streaming mode and therefore it will not work until the dataset author changes their loading script to support streaming. I have opened a discussion in the corresponding dataset: https://huggingface.co/datasets/GEM/wiki_lingua/discussions/8
- Let's continue the discussion there
