### ISSUE TITLE
Dataset Viewer issue for AntonioRenatoMontefusco/kddChallenge2023

### ISSUE THREAD

**Issue by AntonioRenatoMontefusco** [huggingface/datasets-server#1215]
### Link

https://huggingface.co/datasets/AntonioRenatoMontefusco/kddChallenge2023

### Description

The dataset viewer is not working for dataset AntonioRenatoMontefusco/kddChallenge2023.

Error details:

```
Error code:   JobManagerCrashedError

```

**Comment by albertvillanova** [comment]
Thanks for reporting, @AntonioRenatoMontefusco.

Please note that the job crashed because you are trying to load into RAM memory a JSON file of more than 4 GB. I guess many potential users would face the same issue if their machines do not have enough RAM memory.

If you would like to support loading your dataset in machines with lower RAM, you should:
- either change the format of your data files, from JSON to JSON-lines, so that the data files can be loaded in memory line by line, thus with manageable RAM requirements
- or split your JSON files into smaller files, so that each of them can be loaded in memory

**Comment by albertvillanova** [comment]
I have opened a discussion in the Community tab of the dataset: https://huggingface.co/datasets/AntonioRenatoMontefusco/kddChallenge2023/discussions/1
Let's continue the discussion there!
