### ISSUE TITLE
Dataset Viewer issue for TempoFunk/big

### ISSUE THREAD

**Issue by chavinlo** [huggingface/datasets-server#1248]
### Link

https://huggingface.co/datasets/TempoFunk/big

### Description

The dataset viewer is not working for dataset TempoFunk/big.

Error details:

```
Error code:   JobManagerCrashedError

```

**Comment by chavinlo** [comment]
I also have another issue:
`_CHUNK_LIST = json.loads(open(dl_manager.download("lists/chunk_list.json"), 'r').read())` (datasets library)
works in streaming, but not in local?
on streaming the json loads correctly (returns a valid path)
but on local it just thinks its in the current directory (ie.` /home/dep/lists/chunk_list.json`)

**Comment by albertvillanova** [comment]
Thanks for reporting, @chavinlo.

Please note that this issue is not specific to the dataset viewer, but to your dataset loading script. You try to load all the TAR file in memory, and there is not enough RAM. I guess many potential users have the same RAM limitation issue.

I'm opening a discussion in the Community tab of your dataset: https://huggingface.co/datasets/TempoFunk/big/discussions/1
Let's continue the discussion there!
