### ISSUE TITLE
Generate 5GB parquet files for big datasets

### ISSUE THREAD

**Issue by AndreaFrancis** [huggingface/datasets-server#1257]
For datasets over 5GB, let's generate 5GB parquet files (with shards) instead of ignoring them. The fact that the dataset was truncated should be stored somewhere.

---

Currently, datasets server gets stores parquet files if the dataset size is less than PARQUET_AND_INFO_MAX_DATASET_SIZE config.
- `PARQUET_AND_INFO_MAX_DATASET_SIZE`: the maximum size in bytes of the dataset to pre-compute the parquet files. Bigger datasets, or datasets without that information, are ignored. Defaults to `100_000_000`.
For future implementations/features we would probably need a full dataset reading, big datasets won't be available for it.

There are a couple of suggestions to mitigate excluding big datasets from full reading:
- Copy at least first x GB of data
- If a dataset is already in parquet files copy them directly instead of processing
- To have a data lake?

**Comment by severo** [comment]
Yes, I think the first two points are what we should do.

For `Copy at least first x GB of data`: we will have to transfer that information in all the processing steps that depend on it. eg. the opt-in/out box on the Hub should say that the analysis was made only on the first 5GB, or the /rows last page should mention that the following rows are not available (only 5GB can be accessed)...

For "If a dataset is already in parquet files copy them directly instead of processing", see https://github.com/huggingface/datasets-server/issues/1273

**Comment by severo** [comment]
See also https://github.com/huggingface/datasets-server/issues/908

**Comment by lhoestq** [comment]
Currently we download everything and generate everything, and we want at least partial generation.
But I think we also need partial download (or it may take ages to download the data and fill the disk).

Therefore ideally we should only download what's needed and only generate what's needed.
Shall we use streaming mode on big datasets in this case ? :)

For big non-streamable datasets it's less easy but doable (maybe with a LazyDownloadManager). IMO we can see later if we need to support non-streamable datasets ?

**Comment by severo** [comment]
I have no idea of what is possible with the datasets library. OK to do with streaming first.

**Comment by severo** [comment]
Once done, try on mozilla-foundation/common_voice_10_0 and answer https://twitter.com/cosmos_218/status/1667801640710328320
