### ISSUE TITLE
[doc] Query datasets from Datasets Server: split into one page per library?

### ISSUE THREAD

**Issue by julien-c** [huggingface/datasets-server#1269]
i.e. having a specific page for DuckDB would be very cool i think

**Comment by julien-c** [comment]
maybe cc @stevhliu

**Comment by stevhliu** [comment]
I think at the moment it might be cleaner to keep it all on one page since there's not too much content for each of the libraries (for example, the Pandas section is super short and not really worth adding another section to the `toctree` imo) and because the content is so similar I think it'd make more sense to me to keep it together for now. 

If we get more content for each library (plus highlighting the unique aspects of each library), then I'd be more compelled to create a separate page for each one. What do you think @mariosasko @lhoestq @severo?

**Comment by lhoestq** [comment]
There is potential to add quite a lot of content for duckdb, so yea having a separate page at one point makes sense imo

**Comment by julien-c** [comment]
also makes it way easier to share with DuckDB or Pandas authors and motivate them to write content about it when it's a single page focused on their tool

**Comment by severo** [comment]
done
