### ISSUE TITLE
Pagination for configs with <100 items

### ISSUE THREAD

**Issue by yjernite** [huggingface/datasets-server#1292]
### Link

https://huggingface.co/datasets/yjernite/stable-bias_grounding-images_multimodel_3_12_22_clusters

### Description

I have a couple of datasets where I can't see all items in the viewer: the first page always shows the first 11 items, but pagination is only triggered for configs with >100 items

Other example:
- https://huggingface.co/datasets/yjernite/prof_images_blip__prompthero-openjourney-v4

**Comment by severo** [comment]
Yes, there is a detail here.

- /first-rows endpoint, which is cached and used to render the first page very fast, has a size limit (200KB): https://github.com/huggingface/datasets-server/blob/bdfe97eb64929eaf20979169532aac7312464e43/chart/env/prod.yaml#L87
- /rows, which provides the other pages (2, 3, etc.) don't truncate the contents

I agree that it's incoherent, and we should find a better way to manage this.

In https://huggingface.co/datasets/yjernite/stable-bias_grounding-images_multimodel_3_12_22_clusters/viewer/yjernite--stable-bias_grounding-images_multimodel_3_12_22_clusters/24_clusters, for example, 11 rows are shown instead of 24. It's because the `centroid` column is heavy.

- https://datasets-server.huggingface.co/first-rows?dataset=yjernite/stable-bias_grounding-images_multimodel_3_12_22_clusters&config=yjernite--stable-bias_grounding-images_multimodel_3_12_22_clusters&split=24_clusters
  <img width="607" alt="Capture d’écran 2023-06-02 à 09 51 59" src="https://github.com/huggingface/datasets-server/assets/1676121/cafc53e5-1fa5-4d7a-bc82-1d1032374e6b">

- https://datasets-server.huggingface.co/rows?dataset=yjernite/stable-bias_grounding-images_multimodel_3_12_22_clusters&config=yjernite--stable-bias_grounding-images_multimodel_3_12_22_clusters&split=24_clusters
  <img width="663" alt="Capture d’écran 2023-06-02 à 09 52 12" src="https://github.com/huggingface/datasets-server/assets/1676121/b8316404-eeb9-4a97-b846-1c9cfa5e11df">

**Comment by severo** [comment]
Not sure what we want to do in that case @lhoestq @julien-c @gary149:
1. let it as is (I don't think the number of occurrences is that high)
2. add a message telling that the rows have been truncated (I think we had it before)
3. add a message telling that the rows have been truncated + add a button to let the user get the non-truncated rows
4. load /first-rows, then hydrate in JS with /rows if the data were truncated
5. don't truncate the rows (beware, the total size can be over 100MB in some cases, with complete Wikipedia pages inside the cells, or only 1 row and 1 cell with a complete dataset inside)

**Comment by severo** [comment]
Hmmm, it sounds like a good idea: on the viewer dedicated page, use the /rows endpoint from the first page if available (but use the /first-rows else).

**Comment by severo** [comment]
closing, as it's a Hub issue. Internal link: https://github.com/huggingface/moon-landing/issues/6864

**Comment by severo** [comment]
It's finally fixed in production, @yjernite! See https://huggingface.co/datasets/yjernite/prof_images_blip__prompthero-openjourney-v4 for example. Thanks for reporting.
