### ISSUE TITLE
Do not support datasets that require manual download

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#1307]
Currently, datasets that require manual download show a weird error message due to a TypeError. See: https://huggingface.co/datasets/timit_asr/discussions/2
```
expected str, bytes or os.PathLike object, not NoneType
```

I think we should not support theses datasets, as we already do with private datasets.

EDIT: TODO:
- [x] Raise `DatasetManualDownloadError` from `config-parquet-and-info`
  - [x] #1309
- [x] Raise `DatasetManualDownloadError` from `config-split-names-from-streaming`
  - [x] #1315
- [ ] Propagate the error codes to the aggregator steps (config -> dataset, in this case) so that we can show the appropriate message on the Hub

**Comment by severo** [comment]
I'll reopen, because I think that we should fix a bit more.

Indeed, there are other issues. For `timit_asr`:
- https://datasets-server.huggingface.co/splits?dataset=timit_asr&config=clean: we cannot get the list of splits for the config `clean`, since the step `config-split-names-from-streaming` failed, and the error is:
```json
{
  "error": "Cannot get the split names for the config 'clean' of the dataset.",
  "cause_exception": "ManualDownloadError",
  "cause_message": "                    The dataset timit_asr with config clean requires manual data.\n                    Please follow the manual download instructions:\n                     To use TIMIT you have to download it manually. Please create an account and download the dataset from https://catalog.ldc.upenn.edu/LDC93S1 \nThen extract all files in one folder and load the dataset with: `datasets.load_dataset('timit_asr', data_dir='path/to/folder/folder_name')`\n                    Manual data can be loaded with:\n                     datasets.load_dataset(\"timit_asr\", data_dir=\"<path/to/manual/data>\")",
  "cause_traceback": [
    "Traceback (most recent call last):\n",
    "  File \"/src/services/worker/src/worker/job_runners/config/split_names_from_streaming.py\", line 59, in compute_split_names_from_streaming_response\n    for split in get_dataset_split_names(path=dataset, config_name=config, use_auth_token=use_auth_token)\n",
    "  File \"/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py\", line 442, in get_dataset_split_names\n    info = get_dataset_config_info(\n",
    "  File \"/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py\", line 382, in get_dataset_config_info\n    builder._check_manual_download(\n",
    "  File \"/src/services/worker/.venv/lib/python3.9/site-packages/datasets/builder.py\", line 913, in _check_manual_download\n    raise ManualDownloadError(\n",
    "datasets.builder.ManualDownloadError:                     The dataset timit_asr with config clean requires manual data.\n                    Please follow the manual download instructions:\n                     To use TIMIT you have to download it manually. Please create an account and download the dataset from https://catalog.ldc.upenn.edu/LDC93S1 \nThen extract all files in one folder and load the dataset with: `datasets.load_dataset('timit_asr', data_dir='path/to/folder/folder_name')`\n                    Manual data can be loaded with:\n                     datasets.load_dataset(\"timit_asr\", data_dir=\"<path/to/manual/data>\")\n"
  ]
}
```
  it means that we should check this case (ManualDownloadError) in every step, or do it in the root steps, I don't know
- https://datasets-server.huggingface.co/splits?dataset=timit_asr: the dataset level list of splits, does not contain the reason of the error, because it's a "aggregation" step. It's used by the Hub, and this means that the test that we have in moonlanding (internal: https://github.com/huggingface/moon-landing/blob/d7e5fc51d885cfb6029231635884bc7c0917617f/server/views/components/DatasetSample/DatasetSample.svelte#L22) which worked before to show a special message when the dataset must be downloaded manually, is not taken into account.

So:
- we should at least ensure testing for ManualDownloadError in `config-split-names-from-streaming` too
- we should propagate the error codes to the aggregator steps (config -> dataset, in this case), so that we can show the appropriate message on the Hub

**Comment by albertvillanova** [comment]
Thanks for the investigation, @severo.

I would like to continue working on the follow-up.

**Comment by severo** [comment]
Missing: #1299
