### ISSUE TITLE
Parquet endpoint not returning urls to parquet files for the-stack-dedup dataset.

### ISSUE THREAD

**Issue by deadmau5p** [huggingface/datasets-server#1338]
When calling https://datasets-server.huggingface.co/parquet?dataset=bigcode%2Fthe-stack-dedup to retrieve parquet files for this dataset the response is this:
``` json
{
    'parquet_files': [],
    'pending': [],
    'failed':[{'kind': 'config-parquet',
        'dataset': 'bigcode[/the-stack-dedup](https://file+.vscode-resource.vscode-cdn.net/the-stack-dedup)',
        'config': 'bigcode--the-stack-dedup',
        'split': None
    }]
}
```
Other endpoints are working correctly (/is-valid, /splits, /first-rows).

Below is my test code:
```python 
import requests

headers = {"Authorization": f"Bearer {'**MY_TOKEN**'}"}
API_URL = "https://datasets-server.huggingface.co/parquet?dataset=bigcode%2Fthe-stack-dedup"
def query():
    response = requests.get(API_URL, headers=headers)
    return response.json()
data = query()

print(data)
```

What would cause it, other datasets that I tried are working correctly?

**Comment by severo** [comment]
Thanks for reporting.

First: we should be giving more information about the error (opened https://github.com/huggingface/datasets-server/issues/1339)

The reason is that we don't handle datasets >5GB for now. But https://github.com/huggingface/datasets-server/pull/1321 is adding this feature for datasets using Parquet files, so the dataset should be working very soon!

**Comment by deadmau5p** [comment]
Understood, thanks!

**Comment by severo** [comment]
Fixed, thanks to @lhoestq !
