### ISSUE TITLE
Update docs for hf.co/api/datasets/<dataset>/parquet endpoint

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1400]
To be used instead of the datasets server /parquet endpoint in examples

following https://github.com/huggingface/moon-landing/pull/6695

**Comment by severo** [comment]
It's live:
- https://huggingface.co/api/datasets/glue/parquet/ax/test/0.parquet
- https://huggingface.co/api/datasets/glue/parquet/ax/test
- https://huggingface.co/api/datasets/glue/parquet/ax
- https://huggingface.co/api/datasets/glue/parquet

@lhoestq do you want to take care of the docs? Instead of replacing, maybe create a new section instead?

**Comment by lhoestq** [comment]
sure !
