### ISSUE TITLE
Viewer works on dataset landing page but not on full viewer page: UnexpectedApiError 

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#1795]
The viewer works on the dataset landing page; see for example: https://huggingface.co/datasets/hyperdemocracy/us-congress-bills
![Screenshot from 2023-09-11 09-58-10](https://github.com/huggingface/datasets-server/assets/8515462/f4cdbeb8-0695-4542-8a1f-e46a3830330c)

However it raises `UnexpectedApiError ` on the full viewer page; see: https://huggingface.co/datasets/hyperdemocracy/us-congress-bills/viewer/default/train
![Screenshot from 2023-09-11 10-00-22](https://github.com/huggingface/datasets-server/assets/8515462/1740af52-bfd2-427e-b5b9-549132d3e8c0)

Fix Hub issue: https://huggingface.co/datasets/hyperdemocracy/us-congress-bills/discussions/1

CC: @galtay @lhoestq

**Comment by lhoestq** [comment]
This is because the row group size of the parquet export of the dataset is too big for the API.

So we need to either modify `maxRowGroupByteSizeForCopy` (currently `500_000_000`) and/or `maxArrowDataInMemory` (currently `300_000_000`) to make them compatible.

I think it's fine to lower `maxRowGroupByteSizeForCopy` to `300_000_000` and re-run the `config-parquet-and-info` job for this dataset.

I can take care of this next week when I'm back, or feel free to do it @albertvillanova

**Comment by albertvillanova** [comment]
Also reported in: https://huggingface.co/datasets/RiddleHe/commonsense-baseline/discussions/1

**Comment by albertvillanova** [comment]
I can take care of the small modification you proposed, @lhoestq.
