### ISSUE TITLE
upgrade duckdb to >=0.9 and pandas to >=2.1.1

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1914]
See previous intent here: https://github.com/huggingface/datasets-server/pull/1827

If we apply it, we must recreate the duckdb files created with duckdb <= 0.8

**Comment by AndreaFrancis** [comment]
I suggest the following plan to handle duckdb upgrades:
1. update poetry dependencies
2. increase job_runner version for `split-duckdb-index` so that, all entries are computed again with new version 
3. migration to add `duckdb_version` field in all cache entries with kind `split-duckdb-index` with a default value of 0.8 (previous version) 
4. change /search to validate that `split-duckdb-index` cache entry duckdb_version is equal to a new DUCKDB_VERSION_CURRENT constant; if not, raise an error
5. we can also invalidate `dataset-is-valid`, `config-is-valid`, and `split-is-valid` cache entries (set search:false and filter:false) so that we temporarily hide the functionality in the UI and avoid having errors when calling /search and /filter endpoints; meanwhile all cache entries are being refreshed

**Comment by severo** [comment]
Good plan. Maybe we can simplify it a bit since the duckdb team swore 0.8 -> 0.9 was the last breaking change in the duckdb file format

1. update poetry dependencies and increase job_runner version for split-duckdb-index (even if it's not really needed with step 2)
2. in the migration job:
- (before launching the migration) stop the workers
- delete all the split-duckdb-index entries
- set search:false and filter:false in dataset-is-valid, config-is-valid, and split-is-valid cache entries so that we temporarily hide the functionality in the UI and avoid having errors when calling /search and /filter endpoints; meanwhile all cache entries are being refreshed
