### ISSUE TITLE
Are URLs in rows response sanitized?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2009]
see https://github.com/huggingface/moon-landing/pull/7798#discussion_r1369813236 (internal)

> Is "src" validated / sanitized?
> if not there is a potential XSS exploit here (you can inject javascript code in an image src)

> Are S3 object names sanitized? If no, it should be the case in dataset-server side

**Comment by severo** [comment]
cc @AndreaFrancis do you want to look at this?

**Comment by AndreaFrancis** [comment]
We generate the images/audios URLs at these locations:
- For images, it's created at https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/viewer_utils/asset.py#L60.
- For audio, the URL is generated at https://github.com/huggingface/datasets-server/blob/main/libs/libcommon/src/libcommon/viewer_utils/asset.py#L90.

(Maybe I can refactor to get the src from a single function).

I think the URLs we generate are automatically sanitized, because we forge them with the following parameters:

Base URL: We retrieve this from [here](https://github.com/huggingface/datasets-server/blob/main/chart/templates/_common/_helpers.tpl#L200) for assets (used in firs-rows) and [here](https://github.com/huggingface/datasets-server/blob/main/chart/templates/_common/_helpers.tpl#L207) for cached assets (used in /rows, /filter and /search).
Directory Path: It's a combination of {dataset_name}/{DATASET_SEPARATOR}/{revision}/{DATASET_SEPARATOR}/{config}/{split}/{str(row_idx)}/{column}.
Filename: The filename typically follows the format image.<ext> and audio.<ext> (Only image.jpg, image.png, audio.wav, audio.mp3 are supported).
Not sure if  an additional validation may  be necessary, as these processes are always managed on the datasets-server side.
An src value always looks like: "https://datasets-server.huggingface.co/cached-assets/asoria/bluey/--/abf99ba2de1d5c93e777016bb2634248c7f366e5/--/config/train/47/image/image.jpg" and as you can it just contains scheme, netloc and path components (No query part, we need add any related value).

**Comment by severo** [comment]
Maybe ensure that dataset_name, split, and especially config and column are sanitized, as these are user defined.
