### ISSUE TITLE
NotImplementedError: Copying a non-LFS file is not implemented

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2317]
See https://huggingface.co/datasets/bibinsee/meme.me/discussions/2

Maybe @Wauplin can give more details about the error raised from huggingface_hub?

The data is a 20kB parquet file, not versioned as LFS.

<img width="784" alt="Capture d’écran 2024-01-22 à 10 46 33" src="https://github.com/huggingface/datasets-server/assets/1676121/ea72efe0-2f4f-4cbc-b15a-c673cb215f4b">

**Comment by severo** [comment]
Also: the repo does not have a root `.gitattributes` file

**Comment by severo** [comment]
I replicated the dataset here: https://huggingface.co/datasets/severo/meme.me

**Comment by severo** [comment]
@lhoestq maybe we have to differentiate LFS and non-LFS parquet files when copying them to refs/convert/parquet.

**Comment by Wauplin** [comment]
@severo, implementation wise, copying an LFS file in a repo consists in copying the reference to the file stored on S3. Therefore the copy is a "almost" zero-cost operation. To copy a regular file, we can't do that. The only solution you have is to download the file locally before re-uploading it. It's a heavier operation but doesn't cost mush either if it's only for a few files (since regular files are small)/ We don't have a endpoint to automatically copy files since the need is very low. Also initially, the copy operation has been implemented only for the parquet-copy use case which should always be stored as LFS. Weird that the user decided to specifically delete the .gitattribute in this repo.

**Comment by lhoestq** [comment]
I just opened https://github.com/huggingface/huggingface_hub/pull/1996/files to fix this

**Comment by severo** [comment]
reopening since we still have to upgrade hfh

**Comment by severo** [comment]
```
db.cachedResponsesBlue.aggregate([
  {
    $match: {
      "details.error": "Copying a non-LFS file is not implemented",
      http_status: 500,
      error_code: "UnexpectedError",
      "details.copied_from_artifact": { $exists: false },
    },
  },
  {
    $group: {
      _id: "$dataset",
    },
  },
]);
```

returns 22 datasets (not pasting here, in case some of them are private). Refreshing them
