### ISSUE TITLE
Dataset Viewer issue for alexandrainst/danish-wit

### ISSUE THREAD

**Issue by saattrupdan** [huggingface/datasets-server#637]
### Link

https://huggingface.co/datasets/alexandrainst/danish-wit

### Description

The dataset viewer is not working for dataset alexandrainst/danish-wit.

Error details:

```
Error code:   ClientConnectionError

```

**Comment by saattrupdan** [comment]
@severo Thanks! Here's an observation, which might help: I noticed that the preview works for [WIT-base](https://huggingface.co/datasets/wikimedia/wit_base), and on [their corresponding datasets server link](https://datasets-server.huggingface.co/first-rows?dataset=wikimedia/wit_base&config=wikimedia--wit_base&split=train) the `image` entry of the records are written as
```
"image":{"src":"https://datasets-server.huggingface.co/assets/wikimedia/wit_base/--/wikimedia--wit_base/train/0/image/image.jpg","height":225,"width":300}
```

I.e., they relegate it to another datasets server call. On the Danish WIT the image is instead encoded as their raw bytes:
```
"image":{"bytes":[255,216,255,224,0,16,74,70,73,70,0,1,1,1,0,72,0,72,0,0,...], "path":null}
```

The Danish WIT is literally just a download of WIT-base, filtering the data, and re-uploading, so the `image` should be identical, but it seems as if something happened during this process.

**Comment by severo** [comment]
OK. The issue comes from the type of the image column. In WIT-base, it's an [Image](https://huggingface.co/docs/datasets/v2.6.1/en/package_reference/main_classes#datasets.Image) feature, while in Danish WIT its type is a dictionary, with binary content:
- WIT-base:
  <img width="236" alt="Capture d’écran 2022-11-15 à 13 52 02" src="https://user-images.githubusercontent.com/1676121/201924213-a3f9a63a-db45-4fb3-a8e4-aa9fd360cafc.png">
- Danish WIT
  <img width="213" alt="Capture d’écran 2022-11-15 à 13 52 09" src="https://user-images.githubusercontent.com/1676121/201924194-96fc064a-bfbd-4962-9d34-368b51d1f79d.png">

For that reason, the datasets-server returns the byte contents in every cell, instead of creating an image file (it does know that these bytes are an image).

The solution would be to change the type of the image column.

---

Besides this issue with the dataset itself, the datasets-server response should have been truncated to something smaller (the limit should be 1MB, here the response is more than 2MB)

**Comment by saattrupdan** [comment]
Aha! I just tried casting the column as an `Image` feature, which worked! Thanks @severo 😊 

Code for reference:
```
>>> from datasets import load_dataset, Image
>>> ds = load_dataset('alexandrainst/danish-wit')
>>> ds = ds.cast_column('image', Image())
>>> ds.push_to_hub('alexandrainst/danish-wit')
```

It _is_ a bit strange to me that the images in the WIT-base dataset doesn't seem to be decoded, but apparently downloading the dataset and not touching the images decoded them? Oh well, I'll remember to always cast image columns before pushing to hub!

**Comment by severo** [comment]
> It is a bit strange to me that the images in the WIT-base dataset doesn't seem to be decoded, but apparently downloading the dataset and not touching the images decoded them? Oh well, I'll remember to always cast image columns before pushing to hub!

cc @huggingface/datasets: maybe you want to chime in

**Comment by severo** [comment]
> Besides this issue with the dataset itself, the datasets-server response should have been truncated to something smaller (the limit should be 1MB, here the response is more than 2MB)

Fixed with https://github.com/huggingface/datasets-server/pull/638

It works as expected on the previous version of your repo, that I copied in https://huggingface.co/datasets/severo/danish-wit:

<img width="1541" alt="Capture d’écran 2022-11-16 à 10 21 58" src="https://user-images.githubusercontent.com/1676121/202140750-72ee538e-3db6-451d-8436-789bb0e71b93.png">

The response now weights less than 500KB and is returned quicker, so that the dataset viewer does not timeout anymore.

https://datasets-server.huggingface.co/first-rows?dataset=severo%2Fdanish-wit&config=severo--danish-wit&split=val

Thanks @saattrupdan for reporting and helping surface this issue.
