### ISSUE TITLE
Add pdf2image as preinstalled package

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets-server#688]
Needed for: https://huggingface.co/datasets/jordyvl/unit-test_PDFfolder (the installation instructions for pdf2image can be found there)

**Comment by severo** [comment]
Partly fixed with #691: the pdf2image dependency has been added, and we get a result: https://huggingface.co/datasets/jordyvl/unit-test_PDFfolder

But it shows a new issue (unrelated): we should be showing a gallery of images, and instead, we have a JSON. I'm working on it.

<img width="811" alt="Capture d’écran 2023-01-23 à 11 31 49" src="https://user-images.githubusercontent.com/1676121/214018544-86861fb6-756c-4b6c-9982-d0714a362f28.png">

**Comment by severo** [comment]
Fixed!

https://huggingface.co/datasets/jordyvl/unit-test_PDFfolder

<img width="1142" alt="Capture d’écran 2023-01-23 à 22 28 11" src="https://user-images.githubusercontent.com/1676121/214153870-04bd1a5a-1fa6-4d4a-a5ae-b64098832508.png">
