### ISSUE TITLE
Dataset Viewer issue for dadosdq/wallbed_dataset

### ISSUE THREAD

**Issue by dadobtx** [huggingface/datasets-server#689]
### Link

https://huggingface.co/datasets/dadosdq/wallbed_dataset

### Description

The dataset viewer is not working for dataset dadosdq/wallbed_dataset.

Error details:

```
Error code:   ResponseNotReady

```

**Comment by severo** [comment]
Currently, the jobs queue behind the dataset viewer is long and might take some hours to recover. Sorry about this; we are working on reducing this kind of issue in the future. That's why the dataset viewer took some time to process your dataset.

<img width="581" alt="Capture d’écran 2023-01-20 à 20 47 24" src="https://user-images.githubusercontent.com/1676121/213792376-0b6daf44-fc01-4c36-a456-e978fc6fd747.png">
