### ISSUE TITLE
Fix CI for PR from a fork

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets-server#712]
The CI does not run properly when a PR is made from a fork.

**Comment by severo** [comment]
I'll work on it. Possibly the solution is to launch the e2e tests without docker, or with locally build docker images, instead of having to push to docker hub, then pull from there, which causes issues with the write rights.

Also: currently, we have to edit https://github.com/huggingface/datasets-server/blob/main/chart/docker-images.yaml to put manually the tag of the last build image, which makes the CI experience very bad. It would be better to decouple the CI from the production. The ideal case would be:
- any PR, be it from a local branch or from a fork, will trigger the same CI, including the e2e tests, but excluding the publication of the docker images to the Hub
- on merge, the docker images are built and published on Docker Hub, the `docker-images.yaml` file is modified to reference the new docker images, and e2e tests are run on these docker images, just in case... This way, the main branch should always be ready to be deployed without manual modification.

**Comment by severo** [comment]
> the docker-images.yaml file is modified to reference the new docker images
Not sure for this one, we can still rely on manually modifying the file.

I think that after rebasing #713, now the #716 and #717 have been merged, we should be good for this issue
