### ISSUE TITLE
Dataset Viewer issue for bridgeconn/snow-mountain

### ISSUE THREAD

**Issue by anjalyjayakrishnan** [huggingface/datasets-server#901]
### Link

https://huggingface.co/datasets/bridgeconn/snow-mountain

### Description

The dataset viewer is not working for dataset bridgeconn/snow-mountain.

Error details:

```
Error code:   JobRunnerCrashedError

```

**Comment by albertvillanova** [comment]
Hi @anjalyjayakrishnan,

I think this is not a specific issue with the dataset viewer but with your loading script: the machine crashes because in your method `_split_generators` you try to load into the RAM memory all the audio data for each language. For example for "hindi" language, you try to load into memory the entire data from all the .tar.gz files contained in the directory `https://huggingface.co/datasets/bridgeconn/snow-mountain/tree/main/data/cleaned/hindi`:
```python
        audio_data = {}
        for book in BOOKS_DIC[self.config.name]:
            archive_url = f"data/cleaned/{self.config.name}/{book}.tar.gz"
            archive_path = dl_manager.download(archive_url)
            for path, file in dl_manager.iter_archive(archive_path):
                audio_ = path.split('/')[-1]
                if audio_ not in audio_data:
                    content = file.read()
                    audio_data[audio_] = content
``` 
I guess your machine crashes as well when you kload the dataset locally without streaming mode, unless you have huge amount of RAM.

Instead, you should pass the `dl_manager.iter_archive` to the method `_generate examples` and yield each audio data after having read the corresponding wav file.

As an example, you can have a look at the "librispeech_asr" dataset (no need to implement the `local_extracted_archive` in your case): https://huggingface.co/datasets/librispeech_asr/blob/main/librispeech_asr.py

I am closing this issue. If you need further help or assistance, please feel free to use the Community tab in your dataset: https://huggingface.co/datasets/bridgeconn/snow-mountain/discussions
