### ISSUE TITLE
Dataset Viewer issue for bsmock/pubtables-1m

### ISSUE THREAD

**Issue by nlaird** [huggingface/datasets-server#975]
### Link

https://huggingface.co/datasets/bsmock/pubtables-1m

### Description

The dataset viewer is not working for dataset bsmock/pubtables-1m.

Error details:

```
Error code:   ResponseNotFound

```

**Comment by albertvillanova** [comment]
Thanks for reporting @nlaird.

Please note that this is not a specific issue with the dataset viewer but with the dataset itself: it requires a loading script so that we can load it.

When trying to load it:
```python
from datasets import load_dataset

ds = load_dataset("bsmock/pubtables-1m")
```
gives error
```
FileNotFoundError: Unable to resolve any data file that matches '['**']' at .../bsmock/pubtables-1m with any supported extension ['csv', 'tsv', 'json', 'jsonl', 'parquet', 'txt', 'blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'msp', 'pcd', 'pxr', 'pbm', 'pgm', 'ppm', 'pnm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm', 'BLP', 'BMP', 'DIB', 'BUFR', 'CUR', 'PCX', 'DCX', 'DDS', 'PS', 'EPS', 'FIT', 'FITS', 'FLI', 'FLC', 'FTC', 'FTU', 'GBR', 'GIF', 'GRIB', 'H5', 'HDF', 'PNG', 'APNG', 'JP2', 'J2K', 'JPC', 'JPF', 'JPX', 'J2C', 'ICNS', 'ICO', 'IM', 'IIM', 'TIF', 'TIFF', 'JFIF', 'JPE', 'JPG', 'JPEG', 'MPG', 'MPEG', 'MSP', 'PCD', 'PXR', 'PBM', 'PGM', 'PPM', 'PNM', 'PSD', 'BW', 'RGB', 'RGBA', 'SGI', 'RAS', 'TGA', 'ICB', 'VDA', 'VST', 'WEBP', 'WMF', 'EMF', 'XBM', 'XPM', 'aiff', 'au', 'avr', 'caf', 'flac', 'htk', 'svx', 'mat4', 'mat5', 'mpc2k', 'ogg', 'paf', 'pvf', 'raw', 'rf64', 'sd2', 'sds', 'ircam', 'voc', 'w64', 'wav', 'nist', 'wavex', 'wve', 'xi', 'mp3', 'opus', 'AIFF', 'AU', 'AVR', 'CAF', 'FLAC', 'HTK', 'SVX', 'MAT4', 'MAT5', 'MPC2K', 'OGG', 'PAF', 'PVF', 'RAW', 'RF64', 'SD2', 'SDS', 'IRCAM', 'VOC', 'W64', 'WAV', 'NIST', 'WAVEX', 'WVE', 'XI', 'MP3', 'OPUS', 'zip']
```

Please note that datasets without a loading script are supported for the above mentioned file extensions (also if present in archive files), but the files extension inside the .tar.gz archives are `.xml`. These data file formats are not supported yet.

Therefore, a Python loading script is required in order to load this dataset. You can find additional information in our docs: [Create a dataset loading script](https://huggingface.co/docs/datasets/dataset_script).

I'm closing this issue because the dataset owners have disabled their Community tab, so that they do not accept discussions or proposals of modifications.
