### ISSUE TITLE
Dataset Viewer issue for zeusfsx/ukrainian-news

### ISSUE THREAD

**Issue by OleksandrKorovii** [huggingface/datasets-server#989]
### Link

https://huggingface.co/datasets/zeusfsx/ukrainian-news

### Description

The dataset viewer is not working for dataset zeusfsx/ukrainian-news.

Error details:

```
Error code:   JobRunnerCrashedError

```

**Comment by albertvillanova** [comment]
Hi @OleksandrKorovii,

Do you get to load your dataset locally? 

Looking at your loading script, I see that you try to load each JSON file entirely in memory:
```python
with open(path, encoding="utf-8") as f:
    news = json.load(f)
```
And your JSON files are really huge: one of them is 34.4 GB.

Currently, your dataset can only be loaded in machines with RAM memory larger than 35 GB (approximately). That is the reason why the job runner for the dataset viewer crashed: not enough RAM.

If you would like to support loading your dataset in machines with lower RAM, you should:
- either split your JSON files into smaller files, so that each of them can be loaded in memory
- or change the format of your data files, from JSON to JSON-lines, so that the data files can be loaded in memory line by line, thus with manageable RAM requirements

**Comment by OleksandrKorovii** [comment]
@albertvillanova what is the limit of the file?

**Comment by albertvillanova** [comment]
@OleksandrKorovii, if you prefer to keep the JSON format (instead of JSON-Lines), in order to make your dataset loadable by most of the NLP community members, I would suggest that your JSON files should be around 500 MB each.

**Comment by albertvillanova** [comment]
@OleksandrKorovii has replaced the data file format from JSON to JSON-Lines and the issue is fixed.
