### ISSUE TITLE
Dataset Viewer issue for tcor0005/langchain-docs-400-chunksize

### ISSUE THREAD

**Issue by TimothyCorreia-Paul** [huggingface/datasets-server#997]
### Link

https://huggingface.co/datasets/tcor0005/langchain-docs-400-chunksize

### Description

Hey everyone, I am trying to upload a dataset. When I upload the file and click commit, I get the message saying my dataset was committed successfully, and yet it does not appear on the dataset page and I receive this issue I try to open the dataset preview. I've tried multiple times to no success. What am I doing wrong? Or is it an issue with huggingface at the moment?

The dataset viewer is not working for dataset tcor0005/langchain-docs-400-chunksize.

Error details:

```
Error code:   ResponseNotFound

```

**Comment by albertvillanova** [comment]
Hi @TimothyCorreia-Paul, thanks for reporting.

Strictly speaking, the issue is not related to the dataset viewer, but to the dataset itself: as no files were uploaded, your dataset is empty and it is normal the the viewer shows "ResponseNotFound".

I have opened a discussion in the Community tab of your dataset: https://huggingface.co/datasets/tcor0005/langchain-docs-400-chunksize/discussions/1
Let's continue the discussion there.
